Feature/data discovery template
hal9000-swarm/swarm-control-center-deployment-template pull request #1
Opened 2021-03-03 09:41 UTC by KoflerStefan

template for deploying cube-api, db and data-to-cube funtionapp

2021-03-04 09:22 UTC, florian-fischer-swarm reviewed
In general looks really nice.
Once question: Which sku is chosen as DB server?

2021-03-04 09:36 UTC, KoflerStefan commented
@florian-fischer-swarm: the db-server does not even have the option to choose a sku via the template. The elastic pool has an sku to choose from, but i actually do not know which is default here (seemingly depends on the region)

2021-03-04 09:41 UTC, KoflerStefan commented
i think in our test it was 2 vCores but could be changed easily

2021-03-04 10:24 UTC, michael-rogger-swarm commented
would be great to change to the smallest available option for the elastic pool.
![Screenshot 2021-03-04 at 11 22 25](https://user-images.githubusercontent.com/52399391/109949791-17dde700-7cdc-11eb-9a80-2fdadf468fa4.png)
I guess it is this one?

2021-03-04 12:31 UTC, KoflerStefan commented
okay updated it to deploy the cheapest model for elastic pool

2021-03-04 13:00 UTC, michael-rogger-swarm requested changes

2021-03-04 13:00 UTC, michael-rogger-swarm commented on data-discovery-deployment-template.JSON
> +    "databaseServer": {
![Screenshot 2021-03-04 at 12 41 46](https://user-images.githubusercontent.com/52399391/109967552-da845400-7cf1-11eb-8d9b-c6c01fcccc3b.png)
![Screenshot 2021-03-04 at 12 42 18](https://user-images.githubusercontent.com/52399391/109967582-e4a65280-7cf1-11eb-81e2-6261e7b09690.png)
Hmm did I specify the pool wrong? 🤔

2021-03-04 14:20 UTC, KoflerStefan commented on data-discovery-deployment-template.JSON
> +    "databaseServer": {
hard to say like that, do you have a screenshot of the resources of the resource-group were the database and the elastic pool are located in?

2021-03-05 08:19 UTC, florian-fischer-swarm requested changes
Just minor change wrt dev mode of cubejs.

2021-03-05 08:19 UTC, florian-fischer-swarm commented on data-discovery-deployment-template.JSON
> +  "variables": {
Pretty nice :-)

2021-03-05 08:19 UTC, florian-fischer-swarm commented on data-discovery-deployment-template.JSON
> +              "name": "CUBEJS_DEV_MODE",
Ooops, that is the example I put for running the dockerfile locally for development into the README, sorry. Needs to be "false" or just removed (has a default) for real deployments.

2021-03-05 08:36 UTC, KoflerStefan commented on data-discovery-deployment-template.JSON
> +              "name": "CUBEJS_DEV_MODE",
already removed 👍

2021-03-08 10:46 UTC, florian-fischer-swarm approved these changes

2021-03-09 10:07 UTC, florian-fischer-swarm approved these changes
![image](https://user-images.githubusercontent.com/60611027/110454477-931e0f00-80c7-11eb-966f-f930feb4d1f9.png)

2021-03-09 13:46 UTC, michael-rogger-swarm approved these changes
👍

2021-03-09 17:15 UTC, merged